[client]
toolbarMode = "minimal"
showSidebarNavigation = false
[theme]
base = "light"
primaryColor = "#007BFF"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"
    



